export const countries = [
    {code: "NG", name: "Nigeria", telCode: "+234"},
    {code: "US", name: "United States", telCode: "+1"},
    {code: "GB", name: "United Kingdom", telCode: "+44"},
    {code: "CA", name: "Canada", telCode: "+1"},
    {code: "AU", name: "Australia", telCode: "+61"},
    {code: "DE", name: "Germany", telCode: "+49"},
    {code: "FR", name: "France", telCode: "+33"},
    {code: "IT", name: "Italy", telCode: "+39"},
    {code: "ES", name: "Spain", telCode: "+34"},
    {code: "BR", name: "Brazil", telCode: "+55"},
    {code: "IN", name: "India", telCode: "+91"},
    {code: "CN", name: "China", telCode: "+86"},
    {code: "JP", name: "Japan", telCode: "+81"},
    {code: "RU", name: "Russia", telCode: "+7"},
    {code: "MX", name: "Mexico", telCode: "+52"},
    {code: "ID", name: "Indonesia", telCode: "+62"},
    {code: "PH", name: "Philippines", telCode: "+63"},
    {code: "VN", name: "Vietnam", telCode: "+84"},
    {code: "TH", name: "Thailand", telCode: "+66"},
    {code: "MY", name: "Malaysia", telCode: "+60"},
    {code: "KR", name: "South Korea", telCode: "+82"},
    {code: "SG", name: "Singapore", telCode: "+65"},
    {code: "TW", name: "Taiwan", telCode: "+886"},
    {code: "HK", name: "Hong Kong", telCode: "+852"},
]